### ISSUE TITLE
how to run imagenet training process using multi-gpu cards?

### ISSUE THREAD

**Issue by littletomatodonkey** [zhengli427/TESKD#1]
Hi, thanks for your good job on knowledge distillation, how to run the code using multi-gpu cards? bs=256 is too difficult for just one cards. Thanks!

**Comment by littletomatodonkey** [comment]
And the code commnets that the batch size for imagenet is 128, but 256 is noted in the thesis. Which one should we use? Thanks~

https://github.com/zhengli427/TESKD/blob/c43412edbfb35349584054be61d627116c4f1178/classification/dataset.py#L91

**Comment by zhengli427** [comment]
Use 256.
