### ISSUE TITLE
model有个小bug

### ISSUE THREAD

**Issue by xmy0916** [zhengli427/TESKD#3]
https://github.com/zhengli427/TESKD/blob/master/classification/models_imagenet/resnet_our.py#L358
这里要加上numclass吧：

from：
model = ResNet(Bottleneck, [3, 4, 6, 3])
to：
model = ResNet(Bottleneck, [3, 4, 6, 3],num_classes=kwargs['num_classes'])

不然学生model过fc输出的还是1000而不是定义的num_classes了

**Comment by zhengli427** [comment]
是的
